### ISSUE TITLE
UnicodeEncodeError while print(actvty['activityName']) 

### ISSUE THREAD

**Issue by jedie** [chs8691/garmin-connect-export#3]
If activityName contains non ASCII characters, this happens:
```
Traceback (most recent call last):
  File "gcexport.py", line 1019, in <module>
    main(sys.argv)
  File "gcexport.py", line 919, in main
    print(actvty['activityName'])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 1: ordinal not in range(128)
```

**Comment by chs8691** [comment]
I cant reproduce this issue on my computer. Can you share the original activity name?
`Garmin Connect activity (1/1) [3606651087] Test 2 mit Sonderzeichen ÆþЖ單
	2019-05-01T08:45:00+02:00, 00:00:00, 0.000km
Done!`

**Comment by jedie** [comment]
Create a activity with one umlauts e.g.: ä,ü,ö and try to download ;)
